version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src/log:/home/appuser/app/log
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 外部からデータベースに直接アクセスする必要がない場合は、以下のportsセクションをコメントアウトまたは削除してください
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migration:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    env_file:
      - .env
    working_dir: /home/appuser/app/alembic
    command: sh -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: