"""add log_salt_type to admin_command_logs

Revision ID: 8fb7bc527ddd
Revises: d321d7633315
Create Date: 2025-09-06 11:36:38.251136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb7bc527ddd'
down_revision: Union[str, Sequence[str], None] = 'd321d7633315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_command_logs', sa.Column('log_salt_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_admin_logs_guild_time'), table_name='admin_command_logs')
    op.create_index('idx_admin_logs_guild_time', 'admin_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_bulk_delete_guild_time'), table_name='bulk_delete_history')
    op.create_index('idx_bulk_delete_guild_time', 'bulk_delete_history', ['guild_id', 'execution_time'], unique=False, postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.drop_index(op.f('idx_user_logs_guild_time'), table_name='user_command_logs')
    op.create_index('idx_user_logs_guild_time', 'user_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_logs_guild_time', table_name='user_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_user_logs_guild_time'), 'user_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_bulk_delete_guild_time', table_name='bulk_delete_history', postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.create_index(op.f('idx_bulk_delete_guild_time'), 'bulk_delete_history', ['guild_id', sa.literal_column('execution_time DESC')], unique=False)
    op.drop_index('idx_admin_logs_guild_time', table_name='admin_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_admin_logs_guild_time'), 'admin_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('admin_command_logs', 'log_salt_type')
    # ### end Alembic commands ###
