"""Add success column to user_command_logs

Revision ID: 9a5cf2e33227
Revises: 58fbf2eec6bc
Create Date: 2025-08-31 16:31:07.276714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5cf2e33227'
down_revision: Union[str, Sequence[str], None] = '58fbf2eec6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_logs_guild_time'), table_name='admin_command_logs')
    op.create_index('idx_admin_logs_guild_time', 'admin_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_bulk_delete_guild_time'), table_name='bulk_delete_history')
    op.create_index('idx_bulk_delete_guild_time', 'bulk_delete_history', ['guild_id', 'execution_time'], unique=False, postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.add_column('user_command_logs', sa.Column('success', sa.Boolean(), nullable=False))
    op.drop_index(op.f('idx_user_logs_guild_time'), table_name='user_command_logs')
    op.create_index('idx_user_logs_guild_time', 'user_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_logs_guild_time', table_name='user_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_user_logs_guild_time'), 'user_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('user_command_logs', 'success')
    op.drop_index('idx_bulk_delete_guild_time', table_name='bulk_delete_history', postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.create_index(op.f('idx_bulk_delete_guild_time'), 'bulk_delete_history', ['guild_id', sa.literal_column('execution_time DESC')], unique=False)
    op.drop_index('idx_admin_logs_guild_time', table_name='admin_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_admin_logs_guild_time'), 'admin_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
