"""Alter deleted_by column length in anonymous_posts

Revision ID: 9d63c31ae6c5
Revises: 9a5cf2e33227
Create Date: 2025-08-31 16:52:14.584810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d63c31ae6c5'
down_revision: Union[str, Sequence[str], None] = '9a5cf2e33227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_logs_guild_time'), table_name='admin_command_logs')
    op.create_index('idx_admin_logs_guild_time', 'admin_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.alter_column('anonymous_posts', 'deleted_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_index(op.f('idx_bulk_delete_guild_time'), table_name='bulk_delete_history')
    op.create_index('idx_bulk_delete_guild_time', 'bulk_delete_history', ['guild_id', 'execution_time'], unique=False, postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.drop_index(op.f('idx_user_logs_guild_time'), table_name='user_command_logs')
    op.create_index('idx_user_logs_guild_time', 'user_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_logs_guild_time', table_name='user_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_user_logs_guild_time'), 'user_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_bulk_delete_guild_time', table_name='bulk_delete_history', postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.create_index(op.f('idx_bulk_delete_guild_time'), 'bulk_delete_history', ['guild_id', sa.literal_column('execution_time DESC')], unique=False)
    op.alter_column('anonymous_posts', 'deleted_by',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index('idx_admin_logs_guild_time', table_name='admin_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_admin_logs_guild_time'), 'admin_command_logs', ['guild_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
