"""Initial schema

Revision ID: d321d7633315
Revises: 
Create Date: 2025-09-06 10:24:39.101535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd321d7633315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_command_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('command_name', sa.String(length=100), nullable=False),
    sa.Column('executed_by', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.String(length=512), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_logs_executed_by', 'admin_command_logs', ['executed_by'], unique=False)
    op.create_index('idx_admin_logs_guild_time', 'admin_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_table('anon_id_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('channel_or_thread_id', sa.String(length=30), nullable=False),
    sa.Column('user_id_signature', sa.String(length=128), nullable=False),
    sa.Column('anon_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_or_thread_id', 'user_id_signature', name='uq_anon_mapping_scope_user')
    )
    op.create_table('anonymous_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('user_id_encrypted', sa.Text(), nullable=False),
    sa.Column('encryption_salt', sa.Text(), nullable=False),
    sa.Column('global_user_signature', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('search_tag', sa.Text(), nullable=False),
    sa.Column('anonymous_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=30), nullable=False),
    sa.Column('thread_id', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('original_message_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anonymous_posts_anon_id', 'anonymous_posts', ['anonymous_id'], unique=False)
    op.create_index('idx_anonymous_posts_guild_channel', 'anonymous_posts', ['guild_id', 'channel_id'], unique=False)
    op.create_table('anonymous_threads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('thread_discord_id', sa.String(length=64), nullable=False),
    sa.Column('board', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_by_encrypted', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threads_guild_board', 'anonymous_threads', ['guild_id', 'board'], unique=False)
    op.create_table('batch_delete_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_banned_users',
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('banned_by', sa.String(length=30), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bot_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_logs_created_at', 'bot_logs', ['created_at'], unique=False)
    op.create_index('idx_bot_logs_level', 'bot_logs', ['level'], unique=False)
    op.create_table('bulk_delete_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=True),
    sa.Column('executed_by', sa.String(length=30), nullable=False),
    sa.Column('target_user_signature', sa.String(length=128), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('deleted_count', sa.BigInteger(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_delete_guild_time', 'bulk_delete_history', ['guild_id', 'execution_time'], unique=False, postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.create_table('config_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_history_guild_key', 'config_history', ['guild_id', 'key'], unique=False)
    op.create_table('conversion_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('user_id_signature', sa.String(length=128), nullable=False),
    sa.Column('original_message_id', sa.String(length=64), nullable=False),
    sa.Column('converted_message_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=30), nullable=False),
    sa.Column('thread_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversion_history_guild', 'conversion_history', ['guild_id'], unique=False)
    op.create_table('global_chat_bans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gcb_target', 'global_chat_bans', ['target_id', 'target_type'], unique=False)
    op.create_table('global_chat_channels',
    sa.Column('channel_id', sa.String(length=30), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('webhook_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index('idx_gcr_guild_room', 'global_chat_channels', ['guild_id', 'room_id'], unique=False)
    op.create_table('global_chat_events',
    sa.Column('original_message_id', sa.String(length=64), nullable=False),
    sa.Column('user_id_encrypted', sa.Text(), nullable=False),
    sa.Column('forwarded_map', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('original_message_id')
    )
    op.create_index('idx_gce_forwarded_map', 'global_chat_events', ['forwarded_map'], unique=False, postgresql_using='gin')
    op.create_table('global_chat_rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_ng_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), server_default='partial', nullable=False),
    sa.Column('added_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'match_type', name='uq_gng_word_type')
    )
    op.create_table('global_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('guild_banned_users',
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('banned_by', sa.String(length=30), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('ng_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), server_default='partial', nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.String(length=30), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'word', 'match_type', name='uq_ng_word_guild_word_type')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rate_limit_key', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_rate_limit_key'), 'rate_limits', ['rate_limit_key'], unique=False)
    op.create_index(op.f('ix_rate_limits_timestamp'), 'rate_limits', ['timestamp'], unique=False)
    op.create_table('user_command_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.String(length=30), nullable=False),
    sa.Column('command_name', sa.String(length=100), nullable=False),
    sa.Column('executed_by_signature', sa.String(length=128), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_logs_guild_time', 'user_command_logs', ['guild_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_logs_guild_time', table_name='user_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('user_command_logs')
    op.drop_index(op.f('ix_rate_limits_timestamp'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_rate_limit_key'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_table('ng_words')
    op.drop_table('guild_settings')
    op.drop_table('guild_banned_users')
    op.drop_table('global_settings')
    op.drop_table('global_ng_words')
    op.drop_table('global_chat_rooms')
    op.drop_index('idx_gce_forwarded_map', table_name='global_chat_events', postgresql_using='gin')
    op.drop_table('global_chat_events')
    op.drop_index('idx_gcr_guild_room', table_name='global_chat_channels')
    op.drop_table('global_chat_channels')
    op.drop_index('idx_gcb_target', table_name='global_chat_bans')
    op.drop_table('global_chat_bans')
    op.drop_index('idx_conversion_history_guild', table_name='conversion_history')
    op.drop_table('conversion_history')
    op.drop_index('idx_config_history_guild_key', table_name='config_history')
    op.drop_table('config_history')
    op.drop_index('idx_bulk_delete_guild_time', table_name='bulk_delete_history', postgresql_using='btree', postgresql_ops={'execution_time': 'DESC'})
    op.drop_table('bulk_delete_history')
    op.drop_index('idx_bot_logs_level', table_name='bot_logs')
    op.drop_index('idx_bot_logs_created_at', table_name='bot_logs')
    op.drop_table('bot_logs')
    op.drop_table('bot_banned_users')
    op.drop_table('batch_delete_jobs')
    op.drop_index('idx_threads_guild_board', table_name='anonymous_threads')
    op.drop_table('anonymous_threads')
    op.drop_index('idx_anonymous_posts_guild_channel', table_name='anonymous_posts')
    op.drop_index('idx_anonymous_posts_anon_id', table_name='anonymous_posts')
    op.drop_table('anonymous_posts')
    op.drop_table('anon_id_mappings')
    op.drop_index('idx_admin_logs_guild_time', table_name='admin_command_logs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_admin_logs_executed_by', table_name='admin_command_logs')
    op.drop_table('admin_command_logs')
    # ### end Alembic commands ###
